# Postgres role credentials for the honcho database.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: honcho-db-credentials
  namespace: postgres
spec:
  encryptedData:
    password: AgBK47NBBaDD8aYgGMs4GIbH2rRasE053JSmZWW02Ra+aAtJYwio2G8FXN7gHF5rv0GaAb7KtNPYuuui59VGkTjNBAU9MbWw/fWstOcJuOFwGQ72lBkhE56e7a150eLshSSwEmH2o6VIHPvUslhXl0nhPJlKJvoVZ3KZQqz6MmnXq49H6ZkMa0CqYuBvIBzKsP9eHH3atdpaSMJUlswmKkAon+2Uo8rwEzY28N/de2yDK1Agwi2t/c+HH0mWNLTMmnHHvieCJH2s45XLAOpnU9YML7dowjCt8rut4DiIsiQwlrdgFj8QFDJ2yNAuXm1Jb66E77asdMSMuWWuZ4b3G9BDYQ9CK6xZv/Iwb4K/EiYUKG5q6wG9eo21vKgLN6P33zuYeC3c/cthvEcErXpmpJ8RDwlqrkGf2qlbpN5Vi+nDbr1KSNu5qlDEHFTk4ShJX1YcSVBvIQmlfe1pXEafNRWeqpFLgU/HEsf8xIPrP+v1WjO4XGX5FeDfKCKk6j55F4qSpQT9yvrffKGU7QjY2HzSWcO5lUa2aNwxB5aNzTVkuQM35XU354pHarJw3+S4OYnUgUWzf8xzXM443JfY9SkfsRSKDzRFsSR/spt7ZqyIC4Do17e+HBq9upqJrNrBskMkirv+GF3KIIoF3K7zWJAloSyrmkxTxXbdut3jOTftiE6MB6Vt9l7Qryc7khOfKPUgIvQKPWU9eglHYC1+q4hiQ3v6c5L+cX7hKbyt4jAB5A==
    username: AgAvaMsE3wChNrJsb2/cAOWmgno7VtuwAnH/xTs7FH/DwGrf4WY91PKxCaUD77/IQLRBuHaC2BlL95OL/TC/fKD39VMVQq+1TgTGlD1xJqkbrAK3RtZXtr5W5ndcoil//aYdQx5Ksw57HSGYFCXKKJMrmbiPZqlNj3QI//FnvoYHRzG1gwtjLs3qX6w6E/eVrru/0nzdky3TnscjP5srIQWU/5ZTh7vRXUmPPAgQraKeP+c/mwaQ8Yptj6aNUZrkiRc99n7V5j+0RYYAcxYsKVuzVnTjfpuUOyqJtNJ1cH3muXw4mFjDwSv2+4YNi8iFMn581T+U2BtK1OxR7VFSrdZKLE1WUebSCR/bgG/a7Ux9ogE6O+sPvE0p2Z1JAoPt8UMW+3VmSfxYkXUcg5E7/FXyxUz3x2tDTaGWG0nRSPmOpLUsuG7WVSW/I3DlHr3fWxr2i4m2RQEHPhIMWTFcGZqNmPE2+eVDj68KR9P92Opgi6fHF12tBLj1YO2nWfIVariLm/2Xmv0JMI7OgZ7XlL0LjQBdhxLP3xqdeziZkDQr+ziQi8qkQ+9g8juvxoaMN7KaJffDsU3Ygm4NHwtd0vffXKW68f5qA+LUppLT67R03bkb0z08IdXAIbrmDEgVpBpeUj4Ob2PBeB1fxtqA/0bgBxNgPFfApk37/EYHs/5u0cqqkeDeIgeot2AMLvKj/Qeg6NRJr/M=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-3"
      name: honcho-db-credentials
      namespace: postgres
    type: kubernetes.io/basic-auth
