# Postgres role credentials for the honcho database.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: honcho-db-credentials
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  encryptedData:
    password: AgANj04WBqhK45p7phCo4eWoOTR7aqMZT1KdOE1XSWzpaHWXXCIsE7NjlknqUmDX2ZeypDQjhjk4PLt6/zrDbkEZPL/J/U8bmffd3ZPmPL4hcoIB9AzAa4CXbdmm/9jpbcsmUZpKVudVY8LkNw0+twWC9BKCTGzf21gT1r98smV30Rx8yXqmxL0G9zHzxmNm3riqFliuZo6Nbhf/Zy63VoD9C5BFsDol9TEvN/dws9VL4h0KXZgXSkfXBd2QHFBpNrStfH/MwAUzlfvfbrWRHLUM55pSzni8/weiTPjzLUujvmDtEFMjo6Y0tQkKrRXErm8VzJEWf9lhX62XMCQDBKxGAmPGZyRtP1m4LLRxNu4FrtNiv5DvFm1ImgEaj63Yh7D1rs60Z1y0Ns1JS48J3ijLRSzkkg5yUz3nkD4bq9JtOIh6anns6X0A3FohM/IBnl689BVpLryDRPRRjb8zVK+0kCnMOci82zu3XIq4LHsTCcCi0T6BsO/o+ZM+aHNxS7XCEYb5JVfSi1Zwb5gLfXRjL/BIJvW48YKARwg670mBG8fBvHBJXLHuZi78DJQhFW4uqeRfGSk0kunMobDrPV2xNkIG0kIfPU2jYYGocKY+yixLN4gwJIl5eyZ5oWVRC+LpVuFz+0qZBRjFbpWIxFgadktPjcZ1deB6loM6xXSY5cxWfstfJjxlOb9HVQzVoZNHgFEChYwMb4F81O8CU7lxJZl4eGDjjrgrgYPh3uSTyA==
    username: AgCHXqiJ1Ly4EEI2NEgT5lE8Zeon5VZYd6Rv5SMkOfDW6Id3+v5vljZZqmYzCIEqZucu5WVTbmBTbT7sr9/vs1Zb30uIE3zAGhd0UeAj2jVwA04Rp+AIF5VSLnziyn2It1iR3bogQR7rXUALtscspLyC3OYZyeizANgV5boSau9PKQR7yMjMobkxYpGf7T5qmG783J072z5T9DY5H1dwKq8anBXQc7p4JLNXOzv7S1K71NFPxKNmy42qTZYLsIA9BQC+FoRAnU/sn+GadNRJ/D8MOV05Oqe6fuqWKmxPv/zR4tnNsNHb7S0XOod2A4VWnA3zMLckXC6pxqUTWtbNEoXsSLY3xcHLipl/d3oV+V8AgHsGO2WRt4ui04+EXRHdWfiy6DgGEOQXO7JluzCyIdpREyijwkW1WNHBTsKi1MxNmDioC/oJsucramqmGG3XW/5+mKPCpJKQtaQw/FEgUNVCSXcgP0z89PXC1t/g4ecGpq4ZGR2tHX/2r2DX+NYBEDPjdx6QbiNlvT1GNIGxR01PSZF0NIUIaWcRdffMaQhOziFCP3oxrhosAqbvArx5Csvuou7eMfMdnF8x19tYkgDCdJJ1ceJX1ROLTWlI9yTnXimOqhJ1RbGUuFRRmyGvoYaBxwGJF5VX+ptxQ+ojuxJo3w5wigASEbiut7AXiXY0llKgbsOLtT8vQy417y9cE88JSNMUd4k=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-3"
      name: honcho-db-credentials
      namespace: postgres
    type: kubernetes.io/basic-auth
