apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: librechat
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/Taegost/homelab-k8s
    targetRevision: HEAD
    path: apps/librechat
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: librechat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
