# This is the root app-of-apps
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
  namespace: gitops
spec:
  destination:
    name: ''
    namespace: gitops
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: https://github.com/Taegost/homelab-k8s.git
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true