---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: route53-credentials
  namespace: cert-manager
spec:
  encryptedData:
    access-key-id: AgBzcGSl3INOO1U3ORA3oyZ2rPQ+1bvl1NI77GN8pZ5NIVAP6gUKVWcat+N1KnTypypvDfloE0afecRZblUztChVx7ocue3V6pnUNDLUH0wbRsmPlgoX3lB94p4aLrFGDuZsuqucTYnLUth/Gcw93YTp9MY8dW2H665HIqqB9kYzqAflIHXsHxJ2cpE7fVi0K6LgTm66ManvAsXwsKLcSrEyzNoyqG06lkrPurqEGU1Es0ZTkPAflxmgItPNuYDTr8NMd32p7dMZwgbvHte+vA9S8pyPuF26VtCImgHNlAC82Oo31/gMasdMrDpxubj7zz9gtd+VhYuPOOwSWM0LW6eDft0ExPuOVDIvLRCi7w5mTcVhsb01Mwpyd8DftLRwXJ/4836nD+NMWx8bG/3199CzXflVQTPJjx7gdr9F6fF1iBjY8OoDw/z+ksjHFDmNIRRuDAOUQv+kBIyzS9qf7XU6W3g0J6PM90pZf4vmZxJdzrPnwZIhJphd7mSfdF/HJENrIE+XaKQYzVbSBytszWzpyZ/P3ut6BPGSN1j7vwdoEuu10eEzFs4g047mAlGdM9je/pLPMSoZ+NSDGJQYkPLwWGIWukrfeBUgfNF4mQatZpx93U+trO6wmNQgoQAsNCpO4pd1Ga+CfhdF24iLSl3WV++r+0E3t0/62COU4EtEZO0J8I/d4XAr2zXPT1dtz7xglAFDEyWnlBpuXalCih5Py02nYA==
    secret-access-key: AgAhqCeH3zBtlnbI8rvl+i1atRyWk2n3sheKTK2xIW0vgUbbYvTJ8YndwG13zNs3ifhpM8T94tydK2wHgCMi9eVdRwCpgcGJNrIKfzft4c8u716IGehqfo4pb/4KvOvWt4Tiur2IaKQ7BKwuDMK5MspUr/NGsc+nWm3sHYHma3hgFA+dqCPsnpatXHxOIaLpmW58U/Tv31fOOSpZg0dA/CqUYL6BwHnF/+aplkH+Vtq8NbEa/Kd6aHna+lM4tYAMR/NM0PUO2c7FpLaAdayWUkoL410BmdvJW64A2RFkpNDk0heQlWL9cj5UJWEKHV9jiv6iTdvgoucP/ZFiqfhMDCeGY1HRyi4c/EPuRHO7dY+PD54H1Po0SZaUcoUiaJ7GgoEWhuhcw50B3EtX4w/eqFAiLdzkzHkbZ8AtJuF4WIxRZ418trZ/QPCoPMYk3DqR7msUBRn+q7oBZohGOHT9/d69DUYmYLnKsH6E05MTQNqbWMOCfaFmGhcuyija/+/NoJ733xXFfoeriEJuML31MNkcQK25XtaUKc0R+7oErggOeBJYv4bnbIZgpvOJ9gGvsuo8r2cw7Jh0J05UcYoudoJUhilrWbng/TYInC6BPTwhS7Qh3t9BrhHhvCDFX6LU+Fx1Vyfv9WuiY8KaIV7FNScXuxUDEIy9ham3CVbjJ7W6/HCOOjQWKuWYxs7b6y991wVih4WXjPRBwE9GYawWyH18FrleRZHV5MDlrJZBf+wmI7lUkAr+EMd3
  template:
    metadata:
      name: route53-credentials
      namespace: cert-manager
    type: Opaque
