# Route53 credentials — taegost.com
#
# AWS IAM credentials for the taegost.com Route53 hosted zone.
# Used by letsencrypt-taegost-staging and letsencrypt-taegost-prod ClusterIssuers
# to complete DNS-01 challenges.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: route53-credentials-taegost
  namespace: cert-manager
spec:
  encryptedData:
    access-key-id: AgB3PdYe9xWcsOrdvXis5VtgJJvw9z4FpR2qOZxlVmuhr7BFSxE9DTjvq5IIjo0WB3eU0N6uZL+OqpMlPfSq2pJoL4l1jaZvCh3Do3gWd4HYop6IxMfw3CnXbLsImrSrCZmxfgedmSSoNFiNojqkxWLrEZqYY/ZNaGVXVZPooqxTKlERlTITXxrW+3LJsn9KUPMEN0fBqZ27snQqmWoBO6/uLgaybe4f0dX4PyMhvM9XMN8sw24mjaZQamvfVuG3nxuwHx+KKZYhBbBAMO23AyyAmxCMajHykLBuxbhyLLLYrUJwGOzPJcc1DsMaaWBsq93CmNKugikziNMh5xsryfg5dl7kBoxgC/Z7K4Afjr08A4KqxfoFFRHgXPTSlkYaGWKIMIKRMe02xFFuafeqnUxFntBa7yu0+X27Y4rpsMy3XrP+yb4kI3PL7TUUvcGRhaOFISUaB5y566d7gg0pa1c9HHdDb+mtdqr018SQpylMVN9GTmdVH1E9xxvUYXJxyflgXBPXgUUB69sV0f2wloCCK851uy7+8gO1kZGDpxSkbbg9AuTg57KLGlfyjfZf2UApsfjHiILbe169DRd4JUXbdUUVTNty3M4aCG4hK6bk5YDcM/w1Tqx+V5L3X6kBKvrcKkH58sIJy9Wre3ed9/zYuin9fUUVegDKE49CFXFimtuSZkf8i19bnkRb/KNVB9BZchqqvJuTbxnzucSLOMz6MP6ITA==
    secret-access-key: AgBV3+T8Ixh82ygJkNSrMU1yAhSEnQIc4ODaL2G7VoT7MmTzMFXOFIaB/RXqbDImnroHgZz4MunltnOJz4s+iMNhWDGwzdViWH6WCZV68LWSALyKbMglj2cAIdm2UZbCJh/gf3GnOOKOVwwv3b1Xmz38yGBj5ALw5bTLLGM6ukITAPhEbAMCUTdsxEU3CmWRVvpSQLDDgk8TLSG30ArwU8vCyuuHQmioLmXnyqR5dgqCOgT1/+hPC/59MjvzkFlySNZnyRmLDn24V+kQ7QYdK9ytwBA63MEFrzeH83kEJTKVPYFnV8LD31eHeoG8kI/HitwOYYFFKt0Tl609XluaqJtTGIOqbmIBf57dVImCMzuHWlUQVKaX78OHAHtCfNtdrAPL+di9OMVQ/9wzxqD+ylPasGI7eeicFpKdFLvyBLaeWvWqugwnu5fsNpzcttaWUkbf3vBx0sc4Tvpv0Qm3BipM3fhu6x8zOK2BHNN5DcNpBUrRjnAc1tEb/bGDAHSofSAT/ZQtPl5gKW4Po9u3XTnth6QyxJIN9SjBom1QiQz1e3Wv+C0VU9GE3vsjzMXBonj+nd2KT57xqZk7kRJ0pRj0S/7WNz/q9B70V1urc/taLGNW++fFyXgO4EycW/pSEt/RgzaSx7WdDn3q29H9V57ELINnUx/ofin8FQwdw2l2VYYhAon9dPqMONjasZ6nxX3pg/L3c5CqeTw5Z+uPs15DwwfZOxvSimjgrfNGivXgytCVBkZBx954
  template:
    metadata:
      name: route53-credentials-taegost
      namespace: cert-manager
    type: Opaque
