---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n
  namespace: n8n
spec:
  encryptedData:
    database-password: AgCHs4LKv0t8vDSOYpTmwStRZ1giZK/93SfelW074dj+iWdKJQaPdtbgMQtoWs+4nV2IukYTIzdgIm4kKzambVHy6jo+lxbZZAeAYES5VfFx44tr2UYCtQ3xaod/sN3cLGoJa//mWUtW880nyJqpsifRWIQYMk3l0vZyVt3iRhg8T7yyJI9qj2lX5Q3teC7SWyP8cWf7utKsVN8ywn2dl9RxXfxgCeoh1WGw0riY/aXOGPwxftOBVfBHQzbUh+tequPd3LHLfMnwhhxuEyOWJX72lgNhASQmxSb0GL3IrVWTyIMlbdcyMM7rjI3UpGdroLa5VDJXXYxpvtSdgob9SOcQNwG746dr1onSi9az8LsMyCEqGyOLVjMD2hZYvv2pqVfSvcdDNiiFZxpldx1x51lWu1O7GqZbOR4Vxkl5cWwtXVpinpkHK0h/ALTRIIEdLKMsgOy/eH+gqbhMQqi/8zRuuOfh6QuY/lAIws6fP0q5f/IZccmjrFVVw2GTxjklU4NEphqMBGgGOnF2M1mEu85a/FQsG1MVStdUSxmJR3litdNx6xLWzfhiSSZm1yXrd71BQ/DYZxlMg8nF/WsJR4+AGM7t7bm61LrcdvQtTyCe5pKY/b9VwvLBQoFqWTvGZpRi19iZZN9JFnN0rmFe+fdWh0VDiuMbp1LImQfeGzKRvEUUppuI7fP0/XJZ1Bgs0lFSMKlalVLxICV/faHX0Hkrd9gyaPdJmwKqkxyu7Bof4Q==
    encryption-key: AgAp0iU7OaLbOk4C3EoRj57rqII0nXSNb32XNkTWhIinUlBRYf8nXWDUS7NQp/3EH3Va91Yc5E/73PQh9ZYjygKeYwS19LP4OP4SMozk0T3uOCnVR98afls/vcwP0lda8dn53O5/QyE0smLa9dqafIlcS1dIZWBC0EVYmICQeuym+7dktMnPUGcOTNELtSQYnesXmgLQSmnW1tSXYD6JVcyiyT/mTYMY6FtVfX/qPcdRaAfzt45+40a73UMvGhiExCZDekXj6jPDfWwDiEjMF5+YRLowZ2ER48FQGh//umI7vEtuGXHvgfnNAtpXGttaqTE8dBixhqnEcA8cC8j5JS04rJRrFPlI4wXFVXeumRMS4IjyqEIyX32eSZ0xYAtnSFkUZMwQL+ckYS9U9Ra1xM79mfivGYohKCyJDNXGBRHIPNnRcSdumk/t8pwt9IpZU0T2c5z8LtrFvObqvXFoy1IT0YjLM2OwCYwbI1gJz/Trkrwz31NqzKqHeKoPQfP7b+iA2kfVl25s2UrK8269nIA82piTFaqlYSSc36kIG9EaerxSItaxNAMATcYZLQl/Q3vBwHd5AYR9tYZtoIllOYljX4MLRpbE0DFnCnAIOKfcmAltO26IpNtzy4cHonnOJhkg0i31OEgqxpwVBm7Q0rKxWyofnnahP096khHRXr3GaHlVqgt97WJeqroIDxOeB5mgxzgCj58M8Bo8jKyGxjpfE86TVpyjIW24bEW4aZeDBQ==
  template:
    metadata:
      name: n8n
      namespace: n8n
    type: Opaque
