---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-db-credentials
  namespace: postgres
spec:
  encryptedData:
    password: AgBwDXNQYVGm7G63LQSsqIrmJGSDwsidLlRlrQAzOZZ+da0yWyTA8bb5BbCdSzVk0R4re/1bXOx8rLuq+qsujeSNL6t/qrN2r/cFo3uUGhGExBUmpe7gSCVhbTn1aet+rXKDAH3TTBB4xXmLoKXwRe3YvkvtO29gtFOrfE0HkOIhd07YMW53jrymrvEN0KC2M479SS36+zKmFnQaecVB3gd7CV9FiuuK3+ePyDpgZNpsnCCYQDafzYUWl5U7SPHX+iybR1/s0n92TU6zw7Hixk5nZGOvS0VuEBqfjBiz64ItffpHCL49dCCFVIfbsvW5DkK6DjCnleSil1/OLY1ZKE14LHra1NcToHKYPyeygQQmzGW61kJ0HONEt4RG1rU3n2SDHlctuz32Oo5fl0pm9kQRRf8s8Y3nEISXDcnfBSlAMA4hoJdESUVWoiVd9ClCTN/MMmoGdECM1lEZmrWOu5P6E0VKHCByq0REDSkmgEzyEu+CeGksB+TqnMlH6BUlqK6aMNy4yq3skv0+RfQHp8mUl+2KIlR2yuaEZ9b0Tdb55SQb7n4F4kO1ubdqVGhWrA/0JFaTDCJ977wTMAlt7jGnIiaigcpqUtVypybtGNiFU3PcQHeFNnFkny3gL7VT4Cdf3m7hTEllu1cmjIYqPX2cuRQa5H6Hh+Y80fqg+GEy67TW9qpQNO3Vj4omcXJa7YCwrEtwejMj8W51yr6q/rh/b1KAxsUSD/onPW8stzRcXw==
    username: AgAnMlMNRSLJXD9mg2/BtfTTixEfE+4vI3tkVRlE7BZg02sC416FOMB8IgJ4RWTSuvGYB6UEJ8vEhAVjEN3zudRvQQqsGc+UIRCc5bI04ydjDfrqFlFhOr6503UTrHmwCOOg3sfphxN9a2k5wg/hgxqBo4hScKzf/Z2Gkd9zywiUN+hOMJyVa7lZ0qAFDV8XO9KbLxkatals9xfbX3dITgwVGV+DZKAy1TBoD1gt+Mo/ncZkn6Q4RTdqn4ukz5LhKw5bUqVUs6oT45lwCAb2eBfDkwQ9mQ0HhjC3C4tuILW/MPpvMzPuxfOBG7AUzqx9TU7VTQuM1SXgG0tnif1hWmYmtJ8fo6u5ggAG51Jta+jRkng0RFEdk99H/h6u/qzbkvz0TmOh3vCVgXjxFNKrj5r1yH6XQ4buPA0tl13LB6hrHApwQGWZWIrWHGVdQkB7UeLCa28IQvUBi2XStcqBF8pC2HJUb3f0oceAkW0QJzTWoTPpPFYvyCIF/t21kJKAwNsn6uL4LHWvFN3mFeFaoOCuQrXhwG/M5cuGhKE2ancitZlBGK9839E29ktf4zpHRaPTNhPqKfqLGHH8fw8G1x8cvc/faml1In2zs3UpqcHnQn5smZDNQOpJhYAN3J02r1IU8SwigKmgtDhWHJ83CCpve8vSSZVUwukxV0c2WZZJDpmbtbSAdvJxAc2u4hxbTzJNqLc=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: n8n-db-credentials
      namespace: postgres
    type: kubernetes.io/basic-auth
