apiVersion: v1
kind: Service
metadata:
  name: firefly3-importer
  namespace: traefik
spec:
  ports:
    - port: 8002
      protocol: TCP
      targetPort: 8002
---
apiVersion: v1
kind: Endpoints
metadata:
  name: firefly3-importer
  namespace: traefik
subsets:
  - addresses:
      - ip: 192.168.5.12
    ports:
      - port: 8002
        protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: firefly3-importer
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`firefly3-importer.home.diceninjagaming.com`)
      kind: Rule
      middlewares:
        - name: default-whitelist
          namespace: traefik
      services:
        - name: firefly3-importer
          port: 8002
  tls:
    secretName: wildcard-home-diceninjagaming-com-tls
