apiVersion: v1
kind: Service
metadata:
  name: gamepanel
  namespace: traefik
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: gamepanel
  namespace: traefik
subsets:
  - addresses:
      - ip: 192.168.5.50
    ports:
      - port: 8080
        protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gamepanel
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gamepanel.diceninjagaming.com`)
      kind: Rule
      middlewares:
        - name: default-whitelist
          namespace: traefik
      services:
        - name: gamepanel
          port: 8080
  tls:
    secretName: wildcard-diceninjagaming-com-tls
