apiVersion: v1
kind: Service
metadata:
  name: immich
  namespace: traefik
spec:
  ports:
    - port: 2283
      protocol: TCP
      targetPort: 2283
---
apiVersion: v1
kind: Endpoints
metadata:
  name: immich
  namespace: traefik
subsets:
  - addresses:
      - ip: 192.168.5.9
    ports:
      - port: 2283
        protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`immich.home.diceninjagaming.com`)
      kind: Rule
      middlewares:
        - name: default-whitelist
          namespace: traefik
      services:
        - name: immich
          port: 2283
  tls:
    secretName: wildcard-home-diceninjagaming-com-tls
