---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-db-credentials
  namespace: postgres
spec:
  encryptedData:
    password: AgBIWe43HenjEhsZG62hzl1Q0Xs58qFXts0m0fqR4FjAdouHO5pO2/Cr6kxIeXuoE6NiKP0j9qMnXBAi0v52Hzpp6cJSYuPkXHbaCnM1prfICSXG/jc+HXp0R/dsiHrSzx6lRvBhX2dYeOFnSXwV/2HUbzKu7u+iBI/7SfVSxgZogBmK+PgEI/ZBB+K1vIBPE0MUXFEqs5sFT0sbLgU+a7FxbCLJR6YeF8VyMAjU/8ZfDNBXUFnKcqUnAacBD6ps6ENqsi/XzJ9I810n9s3Idl/AFAqVvYB62j8pQmy7Q7FKViptutu0rOmtXBtLlsGvRA73u/rB0w/4T9QJEtD4JumpmFw0RdJCu4yZd0A4gAMgm2TIEj5vfPR/Ip1XZIRjFFVthase+pbjIQ5opVbX6n6eJyE2raNRsG7RP21X6Ur/6vL4sDtpvRBj1NG8QqfshIPoalS+rpDZ5HYZKsbuvHXifoOKwn4F8rmDvD6+ivh2IttOZr/isV7ARzxgqmDmgF07Jz7HtzxV9rnVAUBAfGMi1t0Q+sfinH45rfww0am6u7NZL3G21DfUq0NdRWKpOfjA80z6xzh2evKrbdcY1YUGVxNzTNWp3hffJqrhM9yFS//7XSlfOZdeNRj5acLSaxu4v0uQKxp4Eve+n3XYrntty4yzSe3+f9YOhIYvbvtEdAgVHTGLjm7frUIY6WUbvkur3d7gMpNHk/edUDS/h/r+
    username: AgCa2/jN3efrNrV3Y4aQrGdeB+CVuh/J6E2bwnVV5bSsseM4gxYKmqXd8fTd6SiKIE8/KGCD2NgUnZEQGOTrwDjZbhzKH9wA9t007qxisiBzay3sWsFKofmZvlbeHeGFBx95Jw+zwGpr0GJzWSai/4InUgJyufZDBTxewdr18mfA2GgxEeuijnx6dLaHf2X8x84RSaDX0Df6A+z2TsAP4d3O+MmiF0dT0zftA2NMZs5J7B1o5JT1jAVw19WSEcBNIdgemZ8C9vA77eSDNc16JoguJ7afjg6XLfjBwwQ9/Zy49Due15xn4ao23/l2/aWvZJZvldl1pQY1xQTl5pT6rKyEBBzpicd0o1WYAdEEnHIiN55hxVtyyTxVCnDUK923J32YX3aStVF5GMoj1DWBD+UwlPamQ2y73Vv4Xx4bkHQhbLsn4MgTVfhCEYZxkZEWQHZC/jaFakTPJYSHvGUpGYsvCAPGoEj1GB84mMDqvAXMOl0ayHLWVMBOTovcOFd1x6RB7hsUaxFOIWPcDhj8MhSRxn3nIekBp2cfmXnX4MCvy+KGq5zwI40d2r4731gRy9goplvq45bAUFrRJV4jKFXqwVbsgk1xfscCTi9BxyO8lIQzLmIHJYooEuVfRhvXChTN8rIipV/PCJV6Au28Cpdvteph6YPrFwchhCg6HkyuR9zWTvu5PNXv3PzhEPolmybkj4acD3JN2bk=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: authentik-db-credentials
      namespace: postgres
    type: kubernetes.io/basic-auth
