apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-cache
  namespace: searxng
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi