apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://helm.traefik.io/traefik
    path: ''
    targetRevision: 34.*
    chart: traefik
    helm:
      valueFiles:
        - $values/traefik/values.yml
  - repoURL: https://github.com/Taegost/homelab-k8s
    targetRevision: helm_app-of-apps
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
