apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: traefik
    server: https://kubernetes.default.svc
  source:
    path: traefik
    repoURL: https://github.com/traefik/traefik-helm-chart
    targetRevision: HEAD
    helm:
      chart: traefik
      repoURL: https://helm.traefik.io/traefik
      targetRevision: v34.*
      valueFiles:
        - values.yaml
    chart: traefik
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
