apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 34.*
    chart: traefik
    helm:
      valueFiles:
        - traefik-values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
