# traefik-values.yaml
api:
  dashboard: true
  insecure: true
deployment:
  replicas: 1  # Start with one replica; you can scale as needed.
ingressRoute:
  dashboard:
    enabled: true
ports:
  web:
    # “web” is the entrypoint for HTTP traffic.
    port: 30080
    forwardedHeaders:
      insecure: true
  websecure:
    port: 30443
    http:
      redirections:
        entryPoint:
          to: http
          scheme: http
service:
  type: LoadBalancer
providers:
  kubernetesIngress: {}