api:
  dashboard: true
  insecure: true
args:
  - --api.insecure
  - --providers.kubernetesingress
deployment:
  replicas: 1  # Start with one replica; you can scale as needed.
ingressRoute:
  dashboard:
    enabled: true
ports:
  web:
    # “web” is the entrypoint for HTTP traffic.
    port: 30080
    forwardedHeaders:
      insecure: true
  websecure:
    port: 30443
    http:
      redirections:
        entryPoint:
          to: http
          scheme: http
providers:
  kubernetesIngress: {}
service:
  type: LoadBalancer
serviceAccountName: traefik-account
