apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manyfold-libraries
  namespace: manyfold
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: manyfold-libraries
  resources:
    requests:
      storage: 10Ti
