apiVersion: postgresql.cnpg.io/v1
kind: Role
metadata:
  name: manyfold
  namespace: postgres
spec:
  name: manyfold
  passwordSecret:
    name: manyfold-db-credentials
  login: true
  superuser: false
  createdb: false
  createrole: false
  inherit: true
  connectionLimit: -1
  cluster:
    name: postgres
