---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: manyfold-db-credentials
  namespace: postgres
spec:
  encryptedData:
    password: AgCc+5/SlRePJITGw1vTZ4T1QBHQGT5KzftyBwIESnGk6nfOyKlmemkYtAyu7rSfak150lMAWNrdg9m4ZqQ39h9z90YCdzGMlSxJZUsUuGQO5VY/CFr3UGjPKsECn8g3u4EWUY66VCXCEx7yrf8Nte4gksV5Fw/juJdC1izyQyee+RuiE4Hfp4/GnMycy39kXaxT1JF0FFLU6q8xjAmCaNo/uuS6bk36h0r3Ttc7H5k5M/7QV9pI9fmKPXPJwa+Hoh+F13bZ3myVIC1CGQHJcubmiiSz3k6jhS6ZPvqHETJv2nmSlgDG+GtplZE5808HfoZpJOwUJLxTLVkDFnK32Q6/GVwc/VDEmK7GUHrwREUfFkfMjgOUGj+uY9+v5Pf8EqMexH69wpt6uV9PE2EZ+UUUTg5jWAyYTRGzkcTHIq50jdEnllDucr8zAQ98EzDYBcwLyZ/Ruewhy7KveED9+A7NJlpq1baHkGHscM0ppheRUELVOPFKYAyM4kJmItWKgDrLIT0Y7KUIZ0qUS7vlnSckpFAy0alERlI4OYJBmbPZXjElAmeF21+ADHn3g6JtBHMJOZ0NDl/vqU6ZELnIoucU2BXdARKypAkg38k1Wo+ERFqzbEDl7uR7lBBFMvUtRIopMktx9x5NCBe0J3r3n7tXSOM3Xc/Qd0zi+xtUr2j7OEjuRIBnJF9+f1w3le46HLtEhjVvYAeszHmOwchRNsTM
    username: AgAPLjP549bHSPZHjTFr1MHgWncPHeS2Sr5Ef08GjoJNXL/yz90B3y6Vi/ZM3xXjne590fXUB9YNNTx/Vzjn8OjkjPWWraF6FD28XYv3NS6hZG8ZE5v/n7fS8hcZ2q9sW/PI5VuEuNIGzr5Shw6ZrP73HXtxhRotC78azo05BMB36IkshrbrAxZK6kYEb9z53o7pSTj8dPdGLGJzkew7ZOpksuXpNofgNHnnSQVSRv5L4T6Vx9IldrqO7OB5nr0CZg1xEHoWwbtu7ZUsdsWabBQOCZTwH2QSZEvFLVKS9pq5avCdI5xNKA7xGwlKzirB79tF++muyaY9bsU0nFa2vTH6BXjD7QVRANFy5tPcp7f7DIEgjhSJ+89qSv1nA9MLjrP2UDNVIgFyY3rRudV6h/DalgPso3/uDOeL+MKAeMwXOrov9KB+4aMAAcFPf+7SKyDubO2enM9ELTQ02y1JZJgFkL+/MwMiONTzcVanQ3u23+pVBgaYMOjzHXwB8t/4vmm9fwGNxiAR+QpgCw4cJCulxPiJQnGIO1EBQTmmP89CTe2zJPAayv2htffr5TVR4uYBBGy/e71qp8hqn6ETo+1bLD3VNZzcFU1jS/dcS2rkKs++v3kp7p34Dzzytoqo+1QaNXJ7Id131iqdl9LDHqK1YB7M+ZJTezScnBtP3wP2dxlYNpWu9KhzxqUp18xkexgJLV7XeJWuJw==
  template:
    metadata:
      name: manyfold-db-credentials
      namespace: postgres
    type: kubernetes.io/basic-auth
