# MongoDB data-at-rest encryption key.
# Generate a 32-byte random key and base64-encode it:
#   openssl rand -base64 32 | tr -d '\n' | base64 -w0
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-encryption-key
  namespace: mongodb
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  encryptedData:
    encryption-key: AgAbSiPL/DGKFuF5uCnVmdP3+KmyCPT7Ck3Zhtw3KMXJy46Q1aA13FqXwZWSiINKnFkySuSPb1Hg7mtIqcePclL4Xz3TdQgGBPpasCgWvuRRRJBrsKjlzZcLs6ZFj1KjMUr7YI+W7SLptLil8wuKKUnBqg2WngZzeqQxMUenOaFeKVVLhZwpBAD1PmpHcxYPfIpPLZzA+ojbuFGhm9Wzk8PZDc2qDhSmgSX6k7ApHB+JqcW4g60OkJ4RsF3O0sNanSCoV/pgMg7U5kEF0doq7LZyWqCB+unlIYzmEXVEUtKqgN4kKbgGYwqmywayzZLTy+R1pYBpXLMmP05z1lz3YXgwx1e/oAUGIG9vtMgR3mTph6JUjhEMCW/72nIWCIbOApFnMZwd4XCW7Pbcrv4aSUyxU/oMRJVHfxjoHl34llzLldp7wAvala3Oyo0i085zwYMbIonEYxnJYwVLgszBdqh4Eye68gDj6YP/ED8VF5pKzeG5f1Ax80bR/DOH5YWojoaE6Yia3ey9rXSX93CU4G3cQEgm4ToYLtWDBkMx9dfWOYewfQb6s1fJOIYDe9mzg95A53DG/+ESZrCnnxGIjIq64zdOch+0gH+s0a3i5Umg46r/msxZEm8ZU/cu+ByhqWRo/24bKjAH/aFR6qL2/MpZUK7wqnVaWDdFfl9/8AvGBHC4J96xI9RWvi1oGQuVTld/VlPMkc2p0QdAz+w7p8t6bwr/aRTZDBo1rK365uXclWeNw4fXv751z0NcOw==
  template:
    metadata:
      name: mongodb-encryption-key
      namespace: mongodb
    type: Opaque
