{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "basic-auth",
    "namespace": "traefik"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "basic-auth",
        "namespace": "traefik"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "users": "AgBaEX3sToRq06RIMzPPD4+/8dhzGH9aChP8uzRbWmd03mvpDJ1XF87+IbsCXmVczZb7/+o/QdHTLI666xIyFBcSBnfiGTb/LNstYrNc+37FNFD5jNCMPXsL7ZgE+F6voKd/Q8NpOHvIgANHFbcp7gQttqBabIu4UCR4C0M3KqIB47HX48h4EuPHo6/yiHBkWSk/2DHujc35QvJx6j5MRTbQq0oiYYdZB0zHVAG4lFnqmfKhAfQ+2aArLYWIRXAhGda+ZUp6z6Pav6DdKFZh5sCQ+HnfM5glrLIgbheRZ4iCzxGzmFGGS4vRgkTmFY0hNDvzx3lUa/4trzJpFWP5Fi8NNPm7FTJXIJRXJDtG6GPdVPx/mGRGpVyvxiQTYWwVRV7A9fzBC7Gwuem6mSXlw5UW/WVzuf5N9dxaUlf4tOX5kNoKONXx1P615sHoZ8+5rUdX4HhqSHoHEEnYNZeO1Ag/OOhz0SA1icUBtEIqS2Ms+slTbiJo9qRLxQ/LjzJ/kRF6hmT0s2UcBuqiARDO0uPb0B7VbySPRLqzAVwE2IHnjyWvDqToioGHPS7Myprm00CaT0KlGZUdm/f3dPZ2dmX3RH1bb2Rpqh8vWfMFNUUCFh9NaqbGdXOVJtCRJroGb5Z6BcxKOE1Pc00Y7WtTjYSmeD9DZoxm55TPVbMPdekqJIr94IbZqnSOSP86fIsDGHWLvWoDZgm/jTgp/bBSNNVXXKOV3cBbWvfmTqBdWLZFG01kF5u6yv/PkpebMFw="
    }
  }
}
