apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: leantime
  namespace: mariadb
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - ALL PRIVILEGES
  database: leantime
  table: "*"
  username: leantime
  grantOption: false
