apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: leantime
  namespace: mariadb
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: leantime-db-credentials
    key: password
  # Allow connections from any pod in the cluster.
  host: "%"
  maxUserConnections: 20
