# SealedSecret — wordpress-taegost-db-credentials (plaintext template)
#
# MariaDB credentials for wordpress-taegost. Deployed to the mariadb namespace.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wordpress-taegost-db-credentials
  namespace: mariadb
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  encryptedData:
    password: AgB6dRI5w+p0XthkUx6uxagv0o93kcyAl6A2xEJ1uTT+Zw0TW0ukdFILX1xeGN9sgr4nC9/oqV/jSNWDtQRvUnv0SeoONSTHA5lhRk9fvOSCsoaMEbTpcD60cDAjjvt4wl+qlWBeNODlMTeQAmJeA7ovoGFsu2F7OuyOyun6W8CxOUA7lpd2siyfUEsxQMVrhfSoHnlFXH0TN88gd5eObuJd5P+Pe9c9b+sHvgPXc2k//HnRsuZTfTarx4yWMUXF/2H7nPbj5se6LrdqCp3cdP9skytfLldJ9qfMMwwp1YOJz9hsoROHFJTEfDR8OJz+q91fTBvmladIsxK39A/A0yOu5O85g1bxuJ6IvJoMmEzqELluzyK2tECqp1skYlpf2bFvuhIq6/Nn0FASPzxPhTNYtifhGWkiHRJsfHeG7Kr+CZefXQb97ChfpcJRPkC8UAJks/0EYRTPydcp3r7A4ge4cKpu74kUMKu52B7amtyAJVlfcCtqMaM+hfBaK5/JQGNTTMrQeWmQZQIMb59i30aAmoCykvWBoyZdnXmO5h3FpZX2xw4WyVxRgydU4va1DiHyKRe1u5MRVLqZ3y7+VzAFXA5Lpk93XHlLrl5yUEYJZ1hT64gBoMtx3PA73N0k6hriCY77A3PkKHxz64c7FNFlcli/9PBxQFmoUsst4FsWmL8ivuELTg/mHPsmKVdfqoANvrrDr9XXxmiTkqrIvb26gej0/u/U0bfioLcWJ+9LcA==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-3"
      name: wordpress-taegost-db-credentials
      namespace: mariadb
    type: Opaque
