---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mealie-db-credentials
  namespace: postgres
spec:
  encryptedData:
    password: AgCyh0aoURaAeolXMQb20X4fFKKxY+GoLNTROMjMplP3MO2vPfYKwWxMIXmREtOUTrt/gYZ44x1IsyfwZMDBk+COSmgjpHTIwdCnGC3s2+SZp5NQkRAniHcF9vnCjKjJhSCQGyW8jWNKQD/GdcuhYDz+kAmhG0lCwPtr/EpFDnY5KNTHZvwnV6GbnyS5duY0jFvudnsxC8SdE98ig+l7sBFXoz7dwTAE9K4Mw0K7zKl/jsbCn6DFfIrJNjthBGy2LdYuTVsap1kax/VkibV80JzxSdLaiy0glfHKHEF3ahwRPbb7gFp2ZcMO43BkDClxOS2YOxMXzBC0HDxuNuX88OP22Uf9qYY7/hBYQBMEgOfLCaxUmerVXsAE/1VnfzYFMcUIItRLt7xxOm5s8Usj9JDmlGyCUNGGCb3uR+8M55cIw4ZszCKaiNvCgypH9cqAkSu8zZWySZj/g7YKBkAG5RhdY2FK5AoD9ahSoCeepj2/ez93BC3vC2YU3/HP0YozxlyEtDULABl99/MYWlUpXyB2LD38eYqsgiXvOlmwMqXLaSAEycVp7F1I1e/RguhxRZLCROyXXZhRkwy1k/2i0h2Pi+qoaciiLRE4TVCmHojThTnJVpAfO23q6Gz74yuZLAejipjaOnJyLH0sOAZfF8EwwIgivvg3a+Qw+nKUR9cktp822R59MZXQeJaT5ZRc7TSvdlKYF1sc0VydgX8epw==
    username: AgBYkfpghJsjPg9TfKea1NFsHVu0POdE/JKSbEsRc+Px1et6rsz0AisvhTqu5u/SMjV+mbD9vZXWYAhoJPV9OGQ6JVUuji/A9xCI2lGplyC9sk9lW8RTSi5a0LPGby27TmEMpSlyKFbyx0gJb0FhsD2RqsijcV9OMMi6ZQYcmG9MMX2dPhOkY5HckEGe6tc2XRp5aFLDcujiLJjyt63MdumbolgvargI6IfnR0QymgDbh4xNRUPAT4A2p4LGZ7VWr3b4qL6DqcpITEOoqK9ZvAMLs1cQx725AWReF5+M9/VgRXRHc6qlunVxWLw5SF5Jjm25RhJEF09YJatehVMdsKJoZNNfVmqcpLsl4SHYpSWRAS28kRHFGscULAI/nL9QQSJGWlcSO3ySb6pBGWH8DpcVJagbcU2/bQlbLYcxo4sT5/indt13olmT8amcqWyUHVX/MKuyUtPe+Ds6XSja3m6GonotQFhSbbH9n4GhnxdMO0v75IFS8KJHp04JwhkzfCko5LJSrE5iWU17G+O9eu7Y1Pj9Puzdw3pcEqPidM9zsoe3kDYlFZ/8eo6oeUnaUvdfMteBHDjz2FxWqvjaplEimhQHf0HxhM1aS+8vDBTtY1zT2P3pOkiGStupGIdiix+0x9rA9VFxzlVoQA/JTwkX9ZzXO+RW4IIsJ9ZGV3ACxPSlv+afBoGRJK//pqlbPIzQJ+M+bjs=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: mealie-db-credentials
      namespace: postgres
    type: kubernetes.io/basic-auth
