apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    path: argo
    targetRevision: 7.8.2
    chart: argocd
    helm:
      valueFiles:
        - $values/argocd/values.yml
  - repoURL: https://github.com/Taegost/homelab-k8s.git
    targetRevision: HEAD
    ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
