apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: "Host(`argocd.home.diceninjagaming.com`) || Host('argocd.local')"
      priority: 10
      services:
        - name: argocd-server
          port: 80
