---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-superuser
  namespace: postgres
spec:
  encryptedData:
    password: AgCyCPL1LPuddTcWeORvp+Zo6IclJuTAHrQuk+A4YLzG2Dp2g7QiQZ0Jc6EQk7NYrQd+/gn46DLon4lR4tNnY3J/gXkcRdrWi/0ztfYZ49CESDcaNdY1dxFyH/8xV1M+HXZtpJaGXSuJvtcij9Jvmx4nnj1/uEX6rvXadpW2NcCcp0bJYHJScq2QbWIwMid9RiYw6FRzQavWtHE2orzEyJqno+zPZ6TfI2pG4eLsll/ExOhRBVGFNPu7CJn/sBFUmVa3cZ00OfBzBL3vqNuCZ3FfMlPzx01gznmcKjK91EMEAMsxqPjLIkEreMdb2GmXUGDoheHOx4vbXjYoRGF5EgzthRR+2YE9mF1lCjDLD+8aWx7kD8+HYEFBusFL6nMCCf4IdX1Z/LGq0Iu5HoxzTwSv2k5RaU/Vbl/ygPV69H43pcMIcs/xKY+/14386jzz1bl36zevnoSDoURkSgH0Y/RZ/R/Dr9ZnEqlzGIGcyx1UjNk+D8YzV6jYqcqXhHSS36irCSTh8M4VRh4QWA5uLGe3riYH9SFHpntqkGWSnKqHrWp4JI4EH8/eu199jglmQmnGkc3Eu4pYCki5i7nwzbgf8bwTQghjrDHxC++2JYVKp3XsVPDpLJvs0RA7jlkSRS8K0HrJGVnlmQyUFnXyuVuqsnkEqy5OzHKVxvOOy/WA5vpJfxGdxri2ZUe4KgxQwLsR9lHsXJKDTqwsnmyjFLW6
    username: AgArvGGtaHNDO5E4Vi3HtpyJ/pdpUDnxQ5P5PySOIgNFNFp8x/Yk9ftuLJx+GJY5VlYNn4YNGk+a7iMG2i7aT2hiS3Oo98u3OEr9ettKDs22quzdlIsFnn0f9/qKtqCbkz8OvZMMr66i9Tt6X6YnfOa43nzgSKWIjglIZdj7qFSaD3p6nbCq18lnV0MN1x4OqWl8NLYOwU0ejgMkd+Wz8IeVsC75PmFGxuAhZI7ahmrOl7wr0XgKsfrttmTh8OUvg9iPBbsR3B8p2UFt77Nnbjle8wP0yhXmNYGQHpXZV6f7vUVuVyQ/ZnupwRVR9RNfxBmjgfFfP4TFjy5eFvV4/kPMddOe6AVrFkNlaCKzqUaTyjqyMgW61PsQLKhwHSXduKccTkLmpBYQ0PRsOm1MJFCqoyk2eCIs33wh/deGTGnXmHfy/nmrnedsJXmuwRC3KalBqV+R5Qzp/nxPLo1R1on37FIOG5nyhgKDMU3xPj7Zk1kmc9W1qnXSJ67R05FK2zFLNiDO233OUiQ/gIghKB5PE7HpCMKUVYBv0A9XFvzI38+99FQLspycAUgA35HuRXjyYvlTmjhbugwCENkKeluwU/zIq8nKod5cjrbxwVykmfBxnde5XPp8Sxdoal7U8CCL3LAia25q2e+PbDs5D/6SUFkvu/s0n/40A3rNHevQ8bXnuW6WWwnzSREq7i8gNF7V6sk0FQe2rw==
  template:
    metadata:
      name: postgres-superuser
      namespace: postgres
    type: kubernetes.io/basic-auth
