apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: traefik
spec:
  destination:
    namespace: traefik
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: traefik
    repoURL: {{ .Values.spec.values_source.repoURL }}
    targetRevision: {{ .Values.spec.values_source.targetRevision }}
