# Secret — wordpress-dng-db-credentials
#
# Database credentials for the WordPress site.
# Deployed to the mariadb namespace.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wordpress-dng-db-credentials
  namespace: mariadb
spec:
  encryptedData:
    password: AgBnSYJBtqUhyU9stpLedu+zEac7R2r1Bjly6b6UQNEFVRoSJko5QGbqVoXaP53H6BZ9LpbdG/yVoBzKucovuxaeckDzOkBWBuVi1WnGevwKTfCq/X4CTc2j1dMrqgmOs7mh2u0ECo8gX2gOzl3CuMSMGGCWmKWhZWl0EuW5DTegY9JM/5TtlWKQVGWQwan+fIBJhhU+X7obsDr++irwCdw8KdQpevRWicSu0eKxlxmkzMN7vQ0dJxl7LXOUhAbfkJDPCks5FaZLXexnRmnP1HZzGL7ekNnHCh85Xem/qkOBhJzZOyhRqGn4wAzNOYe9EZixG+QiW0/dGOEoc7gcr0N/VYxrUXKgAghKOXyGNYuVpwdyGI5cpgJyT/NboMIzl1mzN1RpH/T4sNPuzZ+USqNrX/rKbWPv13kn9zRSqwh1K5GeAn4AtlcD33G73btCVWAwobm1k2Myx1ubagryRlkLfSW9xF/vPXWIVMmXZIGuDjUTrhM8vCriPExfyt3ZabyzkjfVbrIsjXP8Lci1s8k7Oi1f6LWtvSsKgZPRW+TT2t/MR4WhLUsQoGQSGjkYtVjhDUd3sCOJswLJReWIIpnWWkWeFhay/7EakNTPbjNHNJFjSfos89nmAd69HwGgYuu3Dmm4IfN4AAlg0zAcmDueEmzs+AeH0pt6HCD2gQ6ysHPr8MdTtAfZpU5dWBKG219R/e/6qIiI5HKx0NrlE/dnDPM6UwWrtVU3/MaSdjQavw==
    username: AgAanyXw2J/7v7BhrD+DOm66nztVSsYG+Lp9oxup6N7bJ+npFZiIht2iPc+DqBHDlW5H6c0KiilRuw1H+JwvrSdrVb5rhg4IPfqDhk+Uexetr37O6dtm1XbW9gCOr7uR6xSrdfB689e6htI9reKjsI1RWjEy0O+hl8+u4rNSmnCJXDehRkQ1FjOSCurQArT+1L+mbwQnPeSRAEUwipuz+CRctgZ+5A2WlUrb1spP0fQfIOitK25fHn4aK6wuf+AQZvV2tMGcpAd3j9kdxSUQVFGaP8hAIzhQ1Jr28NsR7s5bcmQCYj/cknTz328+ye0HSj/MfwAysZwaIf/SG4mtaJr36rzR5l37YUWjaNs0jN5iBypfXtKoKncYacY0mOTNY9OOiVJLWAbuAcls4BGdKLCB4okhzqXue0/cbFa1Dg5c0M3pp0Xr4VusJXYjOFqSQT9gcnXD3+SRlj8sN14+Ao5bMD9YDc3FYaZRoxdd8lWg7r2/ytu9b4pu2dRNBlmklo8ldBkb3y32x4DTq4zdLPWSstYroyYTpwO19o/hh6NYHUR8hY/HfoYAEgCxykoxWuYYfWx7FlvbCKgoGnz4ohoVnw3dqAyZk+tlGxDZXztKiIj/EHPnJ+mVLLkkr+dS4h8d5Jz2ma49mv45kZ2HON/hSA2GaEqV8Yhi8gJdj8Kt7WyzLN+ifLutOxZSgALukdxWduQc8j70GgJIDsKx
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-3"
      labels:
        app.kubernetes.io/name: wordpress-dng
      name: wordpress-dng-db-credentials
      namespace: mariadb
    type: Opaque
