# Secret — wordpress-dng
#
# Duplicates database credentials for the WordPress site.
# Deployed to the wordpress-dng namespace.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wordpress-dng
  namespace: wordpress-dng
  annotations:
    # Wave -1: Secret must exist before the Deployment (wave 0) starts.
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    WORDPRESS_DB_PASSWORD: AgBpRsabZSCuakqafaxZ2kop6wOrOgcisZz+F0wkS4M2l1hD798b7aaw+7IuA5bXOwHBrB7cKEuOTIQVMMZGQCZPUxjSNEEcDuz+AS4bb2WzQ/YH5wL2KsNenC4eS+mwCS5Dsun9VSH4M/ESc1/ELFd4QhKEM43/X4HMsr/GrBnZoC/hO1cAbVj3CuXMCkjovWaLLl1UbZzZQfDxIXXf/RVj9O6x8d8SVCM7sNbnizaDfTN8VocM6HlMagbkzc4NLh6jG39TeEs8FVwv1XKeyFgNnJAr8ep8r5ZDB4y4dSU/y5H0F2U1i/jVA/Q8aNYnyx9MUxCbGhDuGX2ZHi13833V8bu5nErqytt+M7jGFP4NS9URcQlBOOdDiCF2HoPfttOl6DG7MsBnGJ5/glV7ZQL5e98d7/+v+c4tNES7c4U2wv2vKsU6hQ+W3ew6yRtpFbg/aJ7Lja/LIKDMKXxJEtROMnElgRrJ6lDIcvj15ZmwIIKIet9atzpN19AkxkvnAM13pY+EQGsgHJe2xVPVmRvOeGLVU63ddfA+4VqoDL7swqa6dmKdtd1LYicXHjmHyg+wuPZQEaTJzGDvSQIwxGccAWhwlcyjIYlX+LjAjzaYxHIEtvabxIA61+eH+OmPRCoRrW/EKchlc33A0YUdSUfwlHg2bl1hlLqu99lMuy4MiUNuqWUQWSNWW9y/aQ5A1DIxI9u78lSBB17CJcZLYOPS5tgW8Iu0FG9alNCRL6kHzg==
    WORDPRESS_DB_USER: AgBr1NGVtjDsvIidanno/STGNH6YsX0EL963sO65EnShywIFmkHnNfshlOMhP5qc7l+Hj45eIhO1v+nKCJEIYfKsk8xdzHBa6sTZYFLlVgKGONmtcF9B2cD672fCrdWD25yCub5NNCiF9/eJtF5QEL5S+XgMiIxz5FaEmvJUtLcTXTrldD4BuhZdvjAVCsy7sNe7/Hj8UQZyos1p1WMOkKJhlFvwhIOALbQNYvimhsfDqUE9eHg28KbBX+uvssZRQ3rvPbKKQ9DIt+JLheWyxf8aDGiJszZjNIME6kn1rxmtRjIGklVIVBrALKv5uVkl7g0YfZp9OhFa9pNUD9wGcDRDBI5xMfnoU1Qzw7piEryLzobBJ7SEhaK8vPkH/hS7jbzHz0V6o5QEzY7PyyRj267JV1tTtygfSjewr+h/S6cd28PEJqogHmfnsYsT5rDdV0OCjc+OKUMcGIERFYcsr8QbSf7PdI7OEW57SpBTD9q44XTBoNkhbyUQb3/lgvT+ftS4xaN8i9c1cdWnOVN7bYeGN//qsYHVz8PcIxh+KwbKz14Wkmo9LJtOP4+GnQm7Wwt8su3cPd6Ai0tszp5lmma71Dk906iSiJjmvBC+EjEyTqZoIRhn2GtvfVI5ZxeL55bbiWZF4ynltBbQB3w/+S9a5m39lFvgZqgK7DaCgQHiOj7XNBboXMJL7z9rTDXaotA7e0BU9pAZXyG/cU92
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      labels:
        app.kubernetes.io/name: wordpress-dng
      name: wordpress-dng
      namespace: wordpress-dng
    type: Opaque
