apiVersion: v1
kind: Pod
metadata:
  name: wp-migration
  namespace: wordpress-taegost
spec:
  containers:
  - name: migration
    image: wordpress:6.9-php8.5-apache
    command: ["bash", "-c", "sleep infinity"]
    volumeMounts:
    - name: wordpress-content
      mountPath: /mnt/pvc
  volumes:
  - name: wordpress-content
    persistentVolumeClaim:
      claimName: wordpress-taegost-wp-content
  restartPolicy: Never