---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hermes-honcho-api-key
  namespace: hermes-agent
spec:
  encryptedData:
    honcho-api-key: AgCXJqyrVZrB20+JrBkAsuLoUjgd8u9Y8WQyN6RcyF4wPwZ5o3sE3bGlonAjDw5qApMLKW2sqjxmSsLMfUUXZ8TS4mHpxYHQofCsJTdF8ZyFEP8PWuCwvZiBM+TmXXhRcWgNlhhkFWoEXW3RI141fu+OvfPjzcsAYu/G7RNnn93/CpAfSTfoK4AKnfrOO1tA2AinZu65fCZTLhTySxM7n0JxotdPyJ/bhM7fWJNI8xTqXP1yN4wobh+bbte234F7S/skb35F96UKv7/qszcgqsgdalkYvzZHY9ZqRs4NDRtKblNjdACNeDQr6dzy5NxOS7/4n9n71EytvVgaMJjWCrnXbEzfQATphXr+i/DEB1Taecuwf8gZ01jlM6q/mEuYd/4s2zLihK4EMP63qjjZ2OCUxu95cSZwJNJkCYmCVs1E6o1MF6llKmWvmejJKrSm6eztiJPQPO+Ian9DZ1u0gWFS2fmx4tO7LtbFhIXl5cs+VeHMDAGJrM5wZVKvsXGRo+kAip7zvK3HKDOg53UN+ldVnAAy599mUUmVZhrBeqLVZRvJh5gSEAy81yTzrzyiNZTgXrWvMxbVJaCss3BfTFMhgpOk495sfNpY67ksG9x08BfuPC+9KZligm7fyqZGwAd4gQGc4FF9N31Lr1Emd4ZZINZCI8yt7Np/v7GLrfaVOM6+xMKVgVilNUposKSPKubJ3+O2Lk9afRdbDKVTERdAv7HiYDkLKagtrY47556a19PpeyKX1jb2iSSDQvw8SJBTDHgE/Q18FzUHEAbVdZdzUk7UCC3ARE6fgr/xoKM5SvJE0QpC11inYwIaowEMaN/rd6vR5DtlCoWW5wgG38jTrCvCr3ZkaPZQP+YBFFM4xDOMTRk=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: hermes-honcho-api-key
      namespace: hermes-agent
    type: Opaque
