---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hermes-honcho-api-key
  namespace: hermes-agent
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    honcho-api-key: AgBG9ltBkMN/0UqoBhjIVVdnxDFZg6hTSwZUfH4F1JhUBTM98z5WJpnnQuOxtg1UqO+wt+LDsYNUFIxOE2kO/hBF7yzgulJZChe8qlhYRQP7gvSDFZNA5lP2TUyyuSxR/C4+guZunrKBrp3QVYB1NkoXRLNGVfjHHLVDtXo5s+nIBejHwbWzMAAmupHFQvZR6Pfmx9vXDbqbaT/VuZ6HcHW65FEXkAeyrHN7jWaqKp8w2mZwwDzw145wnVM2XyRXpTP+fSgcEZjsKdHbXcrtz+bbJ4GF2/bnVPtXbo+1jiMYnCuybrrReLCDrMp7VwwUwQwoGoLVa25ZsOmFUl0H3XZCWw1tW6cWZGxsVxUhqvOrbzG9ydj1F0bVOUntXeeVRL9z6kocGDqHF+TnZAZBJBxjyjfK9qAsLFF6kHy16tdfCJgdQ13QS7IVaX0eb8NUGRc9sjCuvkcL3+ueIIFIucJDnTlzvE2q6EXH8XWSH140zqyxhgFniAqO2t7q3EnUrMSrbCrulRszbBZxpboYRbBLOKhpwBd4flFQUcKI2Al8Re2ErY37K1qkkDZ5GNqjU7bZP78FYJvrk7l2ZK8+cq0OZDvhqYFZqfNEuKZmT/3/YXqNcb/mkTDtKbhWaU3GLOhIWq+Rogzy2t3ZjYO/RJHrnU+amwkSugu9F+zUDbU5RZVN8lWcwuI4UggbeDQJQSr6zbiGPY1+3n0yCxlaV1pqKHi9G19YVZtsP2lnV538q0TOl6DVKf2LlnZx7D7oEmuFI52GBmkYd1ohVOuyvuXzUligLqbUoL9441gY70/GhBZ3Q28pCeRuivIW9APtSg4RVKvgQPb0SBCpTFbCMNLP++23v3B0059SVr17MaNIH7BVOayuE1imD08XUaLJBPVNpB3Bxf3/m0NMN1Ifng+XNrun09UE4pChyQTY1sO/rjRYDn8=
  template:
    metadata:
      name: hermes-honcho-api-key
      namespace: hermes-agent
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
    type: Opaque
