# RabbitMQ credentials — Plane
#
# Plane's docker-compose uses user=plane, vhost=plane.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq
  namespace: plane
spec:
  encryptedData:
    password: AgB8mXCD5XrD86NOe8twxbXOFl0QYDhZMOrcCtOs8zQOuFySNUTrEVMHmjE712huysckDTbnLSf0YmwRI5V6nx0nCaNqjnWlzLgkj1er9Zq9o29cJFvhpyRKyjlD6MnZOd8qN4nR5eN1K8lqfIbofvytBegdJ/XwEZhoJOkGM+xWK1GPPlvA49yN390iU93TcondgA+XOsywOf2l19Thfsd/7SrHgHTdVvo0WCnJoLbqRbF0BiVs2/GL+e0pR7N/ZMYGJ8P0FN+TbSGoTnqc4iNHjgJxK5xgtdGs1fn20NOPgTkWyXuXuWIRaDs7OlNOx061v+IpghhpBKp9ptIZ68lUxTVVLFe/nxuCfzQ25Y3eNDoQk+P9lEamvGn6wy+bBlQsteYsyljRy07tiMxLSg1wSjVg56XroQrquYeDA/TieJRUQgS9j201KmOAYrMucOpMPPuHrnDfnodCe/6cHNhIYNdKANgXYRK+N6SugogUHSuBxQCrPCg6kE4eRRmWGTa6q8mJ9mhUTneAn/JeTnESjUHlaA5ZZE2VBXWloUnDkKHkWB8g1RjGlLB4JfJ8tYy5+MGk/tkbvsW6Tkjtn1aiF3JfGr7efP6p6mHXbLuw6p9N1q6vKwfieNekba9WfRDoLYYDdb/2bqNj3RAtoYbOBZTcujLMwY5BW5qyhsXfbt7iL1KTrTTWyZ7cSkmp8xTsSGDKIddiuoPset6qzFt4tzwcXblash7B0+zKw1pdTw==
    username: AgCInRPVgy7eYf2Vs8zVo+oWgWsTAgl95wFEkkCaPKOmn8fbY6yIjXqIbLwvkKvT69JgrY94pHIePAZuf9rGb6MNIOkSKjZ9SjNshKsQeRUkP8Q9AmPqs+77m3V8e2H26DocG+mRusHAnOUwhvtI6Ugmfgdk/G/RkC7nZPW8NCbNR9pKEicZZ+FWAwPMFwyhzOF5g0fl9JlVoAdKrMVIHOc5hFMgA289BZa7ML6giIDDcbGH+Q9hmXBj3yCX9TNjO6EU482q5TUKT9SCrU6kAIiz2EKzfrFw0MO+hEYpRIT3ykSvYt7/KJ11vz/ZxUnWwAVTh9GO5iECYHhgbp/bw68o5mxERRKAAnbyfLUL3b4JG/+FY4Ru+fZH3UhAF/nI3aOqifgWTEkF63Vd1f1Nfmb06CZs6clMP25JO0R6miTt7q9mnM0S4N7P1gLvBGRt4nMV+FeqnGGMmYLAwilPRIDlgr4DQrHBfp0sUUiL/ecXzKbA8tG1mcwUePy/jSmV1tSZ8rdKCg+L39inIJkk5RHs+18J81Dj8la0hTVbNjge+Maw84fO0CDwvcPg2EQfdLmnppmiwoht1WaVmtJAU4NtCpBoRQeFxap5vwcbi79iN3mZiNh34aUsfWhiUH8I3kiBQCqF2eDTAkyTwD+7u/MiExtKPIYL8hXgAKM2SNnUUF5f5sfx2nApRyWoQtVgxvF/dj2oww==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: rabbitmq
      namespace: plane
    type: Opaque
