# Database credentials for Open WebUI — lives in the postgres namespace.
# CNPG uses this to set the role password.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-db-credentials
  namespace: postgres
spec:
  encryptedData:
    password: AgC8detbGY5k6AM/4Fgs1qMrGNgJz6ieoNyIut3qQoaLouI/RnVjtdJt9AizzPcfY9QMp22hg0mKEGJeAZ4sPhd0YGdBGPNRyzEosPqpU6jONcOop8k/re7ibxvBVC2L5ooM7UJIfTP9h085tiCVJj4f+e6EDGDgA6xgG/Uz+K7Lrt6PJcWWiW7hZ2FCIgV57obWwzxVi6f842vpXxWzHig4ZE22BKn6tjqt1ba+jKO0ONFoMjeJOVh+4InxsD+jpVXE7/fcZwlOD9T9A2l7UrQRVxaSR9BZ/6AW+Vx3AFfiW6Sf1nxE/+gsfhVo6v4ZV90NSRwtHiJUfnF6W5kQjTCe/wZGtVJ/peG2fVd45fIIaDQ2BZgZFu2MFufrllMT4ZvM2g24uqCLjkXEcmh2EaoPV5qtIVH62c/zZJvsAXK6hhMx0S+MSjgDavWIvbvjMoUQrPim3WhuVwKU10lZsK9rbX7aJuVFOFINtmJTmjnUb70ODJU1uaYJrX1NeY9dNFhfSKnN3lq1yJKMt8cVhYPILiAqMxIsiZ0EGKnA4qyTXNWOoDNO7Bt5CXcruO61f2glygBM/3jw31Bx+09XWWjpQVWwhLExlsH29tJdUpN75YjoXeegXmTezkKpAbRzcHqooJyeZ8Z7PP94rxYSUyS7JchtAAAa/Wd4PZLlmnBXiCw9cNGmgKoL0+QhQWlsxKU4OYyGb4dcUxtx3V6bbgcv8grDUmShbKvETqo9hqk8gg==
    username: AgCLNLttjezCimfW6BXOQE6NkhcQBxVkrY+I9OIYRumiX8yvgBz9AFsSxAjC4gygbBzo/LJWmk6oXQpRXNC7YdzEyKGMb9EU99wlEbbVNUZJMpvdaJ/n+XlBDq80hFD06a9wrzJRgBfjTuu7hpPVouT5rFbv3xbtNRRiIQIsi20efX3D31Z+8AKaMlEemanWh6Rx7UnC3Qk2OnasK96Kb61Sn1g4jduYpm6AFzlHMR3zsboA1al5lhrgFEb5EaoYzUB19ooJeag4S4YsmOMaVskjqvkPCFi94dj+Pa1+M04Pa34SxTqE5GWInoxtucbQbiGjfOvHUyezIkrfHM2URqk30h4OIDhfLUZWVMnawgkggh8ayt/FnPvydIEarhp+JboQeBTVP1IEhZNdsvuJM1/WN2ulgY4KSbuZv+u9og8Uh7+8tyPQQx+PE1iXetlUJkMUBHxFUk5S4mm4YXzVX4t37i0QysufY2Sm7BwV7nki5EQogJ6bLw9i+cQW6+GFnpif+m6xVNZmDKXuyE+LcUpsbHQcRGnzsOPHKCh+aa28Ev7hEjYauz6AI2Iojs7revQTJtJa5u9kWQ7WAdHZp+adOR3ca7BIOypp34BQjhBbgWY/JZcnBcrtdh9C6HmXgRq8kB4VIgfgwDiVaEeXItry5LQ1lk5fKY9FlW6SAumcDPUCK389qkWH6Plq4lBWcTpwZJo3VnL8wEul
  template:
    metadata:
      annotations:
        # Provision secrets before the Database (wave -1)
        argocd.argoproj.io/sync-wave: "-2"
      labels:
        cnpg.io/reload: "true"
      name: open-webui-db-credentials
      namespace: postgres
    type: kubernetes.io/basic-auth
