# Database credentials for Open WebUI — lives in the postgres namespace.
# CNPG uses this to set the role password.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-db-credentials
  namespace: postgres
spec:
  encryptedData:
    password: AgCkY+vU4fWiOUS5uCew/8Tzmus5cmJgR50dl1cEHOUlcVsN62SLjCpXl+MUn1iY7xHEidLPf5uEfoMDZnCjijcVTlifaeBzHzX0XnM3AxMT9OmtfPzhQrI2gz0h4zG3H4CmnzmuX9iw9D4GqMSuNSFmZv/eqec9iquOxXCoBejIcpL8E9oLEBXSDzvtEwDauVZD3M463xZWIlXBtnfixkjpqxkHRPDbJrzQ9olNrddoGtJEDQPvGK4NQ0Or4Crgg4W/UVa584i6WCgPG3AFnSRwdCtXkYTuCphxQpU2HvzaDAZEGw4Ryk8xxEgg1eETUV0ta+TK79la0MIrpXpDX6XjI33y1kzpSanDCkwyxumzhhlTHUaQxJ2n1kEgUNHKQ5gfpaQGK66MDa7U/jWzbwfpdln2okhFw5SPfCfMwGmxSRGXsUVtIlYWUHvw92c0sI/s9vZHEKN0nl8DlSL9fo3ZN3mEkjx7Q9l775h0domcvK4aYMxdP+/GdL9drwmlkYoECIbHP+gPKVXudcD40NrXWEiW5CfC7hzR2OqdVmlaBRokSJayZdTEUP/Q+cLXOFej/1eHV+JxiBY3Fzi98h6JeQUrTJiko2fMLgguPk+ccdD+eFTt3YBk3SHzab8aRHg6dRAVoZ5tKuj3czjZjDSPAqsp37HOHKXGgi6oIrrM7MDUVOhSoYkJIksxg8m4PRwiicstQDHP5dp5aQS4fm1UVLN19M8rEoJTsdC+wIhMhQ==
    username: AgB3/r7YaKgDUiuPs1ntD04Y6DDYfd5hQdQuBHAL7QzLUgTuQMdKtHY57itgUK17OGhA82FkT7wW2YrM/oJKWcQGRalUpj3W5Op5THPHLm5ZE4yUsF74eksQHLRNvcvkuV+7pdZcpqVyI+2LWnCAq46E0ZhjFmHVVBwR10FDOOFAS2aZDtIM3WT3HoRwvBEi8bFUFcWdOCxPOc+f5mk3N82tPE8N2E+SXAshiAncbbm+/9AEwZ12soYjTDDglpCb5gCrWn3GRg0xMst0mFsvY/jmCcnphLjOG5vvCpc4fxmaNrUu40b5kzqTq0Hn3F81q9OUCHXm1AdLWNCHiYoA/ZbHrnQ0iaZkdmoGkFXMfrRmH9LmOD2/CjI5P2dIYixA7a0ft1nSQ9ijvJiRqVp/ho4sIcOSmroBXQgm9XtSkS2BXfHVOLoYciRI4Pl/RnBFEZZFMPCJtAscucgQA52UOqOQ7y4iW8YIbZDxbh/qHSTShl7J616jjxHRS/dDfhDqtzDOsVXIVYcHsQ9Xh2JqsYlKL96hPsXRkfExsXERn+WLs8vnOExITRdfQdh/xuSjshy5ZAPeKayg7OqaQvmGEOeq4V0lMpNHDZhWU7aZiX+EQLeurQOX0QImUA/JiMSzVO2lwfts19eXYpjpO/0EXsOxjJryNIgMCa52O+XvZ4daZHp02kIR31uW/EC+F8pxZ71TSJdL5hpTgyLO
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
      labels:
        cnpg.io/reload: "true"
      name: open-webui-db-credentials
      namespace: postgres
    type: kubernetes.io/basic-auth
